//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Platform.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int ID { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTIme { get; set; }
        public short DelFlag { get; set; }
        public bool TakeEffect { get; set; }
        public System.DateTime TakeEffectTime { get; set; }
        public System.DateTime LoseEffectTime { get; set; }
        public string Remark { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime Qssj { get; set; }
        public System.DateTime Jssj { get; set; }
        public string Khxm { get; set; }
        public string Gzdd { get; set; }
        public string Gzpd { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
