//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Platform.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuInfo
    {
        public int ID { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedTIme { get; set; }
        public short DelFlag { get; set; }
        public bool TakeEffect { get; set; }
        public System.DateTime TakeEffectTime { get; set; }
        public System.DateTime LoseEffectTime { get; set; }
        public string Remark { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public bool IsVisable { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string IconUrl { get; set; }
        public int ParentId { get; set; }
    
        public virtual ActionInfo ActionInfo { get; set; }
    }
}
